SELECT * FROM GEO;
SELECT * FROM people;
SELECT * FROM products;
SELECT * FROM SALES;
-- calculating amount per box --
SELECT  AMOUNT , BOXES , AMOUNT / BOXES  AS AMOUNT_PER_BOX FROM SALES;

-- checking amount --
SELECT * FROM SALES
WHERE AMOUNT > 1000
ORDER BY AMOUNT DESC;

SELECT * FROM SALES
WHERE GeoId = "G1"
order by PID , AMOUNT , BOXES;

SELECT * FROM SALES
WHERE AMOUNT > 10000 AND SALEDATE >= "2022-01-01"
ORDER BY GEOID;

SELECT SALEDATE, AMOUNT, BOXES FROM SALES
WHERE BOXES between 0 AND 50
order by BOXES DESC;

SELECT SALEDATE,AMOUNT FROM SALES
WHERE AMOUNT >=10000 AND YEAR(SALEDATE) = 2022
ORDER BY AMOUNT DESC;

SELECT * FROM people
WHERE TEAM IN ('DELISH','JUCIES');

select * FROM PEOPLE 
WHERE SALESPERSON LIKE 'B%';

-- aggregating Boxes with respect to amount --
SELECT BOXES, AMOUNT,
		CASE	WHEN AMOUNT < 1000 THEN 'UNDER 1K'
				WHEN AMOUNT <5000 THEN 'UNDER 5K'
                WHEN AMOUNT <10000 THEN 'UNDER 10K'
		ELSE '10K OR MORE' 
        END AS AMOUNT_CATEGORY
FROM SALES;
 
 -- Joining multiple tables and getting amount wrt salesperson --
 SELECT S.SALEDATE , P.Salesperson , S.AMOUNT
 FROM SALES S
 JOIN people P ON S.SPID= P.SPID;
 
 SELECT P.Salesperson ,sum(AMOUNT)
 FROM SALES S
 JOIN PRODUCTS PR ON PR.PID = S.PID
 LEFT join people P ON P.SPID = S.SPID
 group by P.Salesperson
 ORDER BY P.Salesperson 
 
